### ISSUE TITLE
Mobile Fixes

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#53] opened 2016-05-09 14:33 UTC
Looks like some Help Center display on mobile is off.  See attached image.
![help center](https://cloud.githubusercontent.com/assets/17745649/15116449/68b0668e-15d1-11e6-99df-a1705db7bb19.png)

**Comment by humancompanion** [comment] 2016-05-09 16:21
Duplicate of issue #55

**Closed by humancompanion** 2016-05-09 16:21 UTC
Labels: bug
